### ISSUE TITLE
samples

### ISSUE THREAD

**Issue by ch93** [xucongli1989/XCLNetTools#1]
对应的工具类要是提供一些例子程序就跟好了

**Comment by xucongli1989** [comment]
抱歉，暂时还没有着手于示例和单元测试，本人尽可能把每个方法的注释描述清楚，感谢您的反馈。

**Comment by yhq12345** [comment]
我:
你的 DelCookies 貌似 不能 直接 cookie.add
我:
强制设置超时 要 AppendCookie(cookie); 进行 追加 不然会出现 2两个 重名的 Cookie

**Comment by yhq12345** [comment]
![image](https://cloud.githubusercontent.com/assets/10396749/21035741/3dd352c2-bdfc-11e6-960c-b9d6860cbe58.png)

**Comment by yhq12345** [comment]
我操 GITHUB真心 方便啊！！！
