### ISSUE TITLE
GZipHelper里面的数组长度加4是做什么用的

### ISSUE THREAD

**Issue by harris2012** [xucongli1989/XCLNetTools#3]
GZipHelper 第36行代码

var gZipBuffer = new byte[compressedData.Length + 4];

这个长度加4是做什么用的

**Comment by xucongli1989** [comment]
可以参考：
http://blog.csdn.net/chinahuyong/article/details/46503167
http://blog.csdn.net/reage11/article/details/8509558

**Comment by xucongli1989** [comment]
也可以参考：http://blog.csdn.net/reage11/article/details/8509558
